version: "3.9"
services:
  web:
    env_file:
      - .env
    build: .
    command: python manage.py runserver 0.0.0.0:80
    restart: on-failure
    volumes:
      - .:/code
    ports:
      - "80:80"
